secrets:
  root_bundle.crt:
    file: ${CREDENTIALS_DIRECTORY}/root_bundle.crt
  root_ca.crt:
    file: ${CREDENTIALS_DIRECTORY}/root_ca.crt

services:
  backend:
    build:
      context: backend
      dockerfile: Containerfile
    expose:
      - 8080
    secrets:
      - source: root_bundle.crt
      - source: root_ca.crt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-compose.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.hello-compose.entrypoints=https"
      # - "traefik.http.services.hello-compose.loadbalancer.server.port=8080"
