fcos:
  # Fedora-CoreOS
  stream: stable
  architecture: x86_64
  platform: metal
  format: raw.xz

raspberry:
  # raspberry pi (3), 4, (5): eeprom, uboot, uefi
  eeprom_rpi4:
    # Raspberry Pi 4 and 5 first stage bootloader EEPROMs
    version: 2024-11-12-2712
    fileurl: https://github.com/raspberrypi/rpi-eeprom/releases/download/2024-11-12-2712/rpi-boot-eeprom-recovery-2024-11-12-2712-sd.zip
    sha256sum: 156ee1657f9b744e3794ef3d3d97394c07d296c87e568f88297ed97358535a64
  uboot:
    # second stage U-Boot firmware Images
    version: 2024.10-1.fc41
    fileurl: https://kojipkgs.fedoraproject.org/packages/uboot-tools/2024.10/1.fc41/noarch/uboot-images-armv8-2024.10-1.fc41.noarch.rpm
    sha256sum: 4e394b9e5b8a0add992c040f0fa78c3c2299c6e58343fb2651aa623b368e872d
  uefi_rpi3:
    # alt. second stage Pi 3 UEFI Firmware Images
    version: "1.39"
    fileurl: https://github.com/pftf/RPi3/releases/download/v{VERSION}/RPi3_UEFI_Firmware_v{VERSION}.zip
    sha256sum: 9d2bae7868027997c59663d2a29c5a5573c4a846d67d0cd42cdddb5280ee22d8
  uefi_rpi4:
    # alt. second stage Pi 4 UEFI Firmware Images
    version: "v1.38"
    fileurl: https://github.com/pftf/RPi4/releases/download/v{VERSION}/RPi4_UEFI_Firmware_v{VERSION}.zip
    sha256sum: f07d8c5f1e86ac33830ebb45ebf849fd253d013d634824773d89ec41eb0a6624
  uefi_rpi5:
    # alt. second stage Pi 5 UEFI Firmware Images
    version: "0.3"
    fileurl: https://github.com/worproject/rpi5-uefi/releases/download/v{VERSION}/RPi5_UEFI_Release_v{VERSION}.zip
    sha256sum: 2337df318845448ebcc8a6a587d15dccec44b54c665ece21250d2f6170732724

openwrt:
  version: "23.05.5"
  target: x86-64
  model: generic
  baseurl: https://downloads.openwrt.org/releases
  sign:
    id: 626471F1
    fingerprint: 6D9278A33A9AB3146262DCECF93525A88B699029
    sha256sum: cc745af6043fd33b3407cd83d0f5e7476a01fc15328cacf576c083bd7987fcbd
    baseurl: https://git.openwrt.org/?p=keyring.git;a=blob_plain;f=gpg
    comment: |
      23.05.0 and newer builds are signed with PGP key for unattended snapshot builds
      User ID: OpenWrt Build System pgpsign-snapshots@openwrt.org
      see https://openwrt.org/docs/guide-user/security/signatures
  disabled_services:
    - uhttpd
  defaults:
    # can be overwritten using pulumi:config("build").openwrt.defaults.ip
    ip: "192.168.1.1"
  packages:
    # packages for command line scripts
    - coreutils-base64
    - coreutils-nohup
    - hostapd-utils
    - knot-dig
    - knot-host
    - knot-nsupdate
    - mosquitto-client-ssl
    - resolveip
    # network debugging tool
    - tcpdump
    # add unbound in addition to dnsmasq
    - unbound-anchor
    - unbound-control
    - unbound-control-setup
    - unbound-daemon
    # add dnsproxy (big, written in go) in addition to unbound as proxy server for DoH, DoT, DoQ
    - dnsproxy
    # replace wpad-basic-* in favor of wpad-openssl
    - "-wpad-basic-wolfssl"
    - "-wpad-basic-mbedtls"
    - wpad-openssl
    # replace dropbear with openssh
    - "-dropbear"
    - openssh-server
    - openssh-sftp-server
    # replace uhttpd with nginx
    - "-uhttpd"
    # replace nginx-ssl (dragged in by luci-ssl-nginx) in favor of nginx-full
    - "-nginx-ssl"
    - nginx-full
    - nginx-mod-stream
    - nginx-mod-luci-ssl
    - luci-ssl-nginx
    # luci apps and their upstream programs
    - luci-app-banip
    - luci-app-firewall
    - luci-app-nlbwmon
    - luci-app-ntpc
    - luci-app-nft-qos
    - luci-app-sqm
    - luci-app-unbound
    - luci-app-upnp
    - luci-app-wireguard
    - luci-app-wol
    - luci-mod-admin-full
    - luci-proto-ipv6
    - luci-proto-ppp
    # optional dependency for luci-proto-wireguard
    - qrencode
    - luci-proto-wireguard
    # make optional themes available for the web-ui
    - luci-theme-material
    - luci-theme-openwrt-2020

homeassistant:
  version: "13.2"
  baseurl: https://github.com/home-assistant/operating-system/releases/download
  target: generic-x86-64

esphome:
  esp32:
    board: adafruit_feather_esp32_v2
    framework:
      type: esp-idf
      # version:
      # platform_version:
      sdkconfig_options:
        # CONFIG_MBEDTLS_DEBUG: y

android:
  emulator:
    magisk:
      app: https://github.com/topjohnwu/Magisk/releases/download/v28.0/Magisk-v28.0.apk
      modules:
        - https://github.com/kdrag0n/safetynet-fix/releases/download/v2.4.0/safetynet-fix-v2.4.0.zip
        - https://gitlab.com/newbit/usbhostpermissions/-/releases/v1.0.2/downloads/usbhostpermissions
        - https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/releases/download/v6.1.2/MagiskHidePropsConf-v6.1.2.zip
  generic:
    fdroid:
      repositories: []
      # fdroid repositories
      packages:
        # fdroid packages
        - com.jens.automation2
        - com.atharok.barcodescanner
        - org.briarproject.briar.android
        - at.bitfire.davdroid
        - eu.depau.etchdroid
        - org.mozilla.fennec_fdroid
        - com.michaeltroger.gruenerpass
        - ch.rmy.android.http_shortcuts
        - com.fsck.k9
        - org.kde.kdeconnect_tp
        - ca.cmetcalfe.locationshare
        - org.isoron.uhabits
        - com.artifex.mupdf.viewer.app
        - org.schabi.newpipe
        - org.gateshipone.odyssey
        - org.sufficientlysecure.keychain
        - de.dennisguse.opentracks
        - app.organicmaps
        - com.wesaphzt.privatelocation
        - org.secuso.privacyfriendlyactivitytracker
        - com.jarsilio.android.scrambledeggsif
        - net.typeblog.shelter
        - org.ligi.survivalmanual
        - com.github.catfriend1.syncthingandroid
        - org.andstatus.todoagenda
        - org.videolan.vlc
        - com.vrem.wifianalyzer
        - com.wireguard.android
        - de.schildbach.oeffi
