#!/usr/bin/env bash
set -eo pipefail

# Trap to clean up the temporary directory on exit
# This should be placed early in the script, after 'set -eo pipefail'
trap 'echo "Cleaning up temporary directory ${WORKDIR_PATH}" >&2; rm -rf "${WORKDIR_PATH}"' EXIT

echo "Starting test harness..."

# Get the absolute path to the directory containing this script
HARNESS_DIR_TMP="$(cd "$(dirname "$0")" && pwd)"
# MODIFICATION 1: Correct MAIN_PROJECT_ROOT and MAIN_PROJECT_NAME definition
# Assumes test_harness.sh is in the root of the project directory.
MAIN_PROJECT_ROOT="${HARNESS_DIR_TMP}"
MAIN_PROJECT_NAME="$(basename "${MAIN_PROJECT_ROOT}")"

echo "Harness directory (HARNESS_DIR_TMP): ${HARNESS_DIR_TMP}"
echo "Main project root (MAIN_PROJECT_ROOT): ${MAIN_PROJECT_ROOT}"
echo "Main project name (MAIN_PROJECT_NAME): ${MAIN_PROJECT_NAME}"

# MODIFICATION 2: Use mktemp for the temporary working directory
# The XXXXXX will be replaced by mktemp to ensure uniqueness.
WORKDIR_PATH="$(mktemp -d /tmp/worktemp_${MAIN_PROJECT_NAME}_XXXXXX)"
if [ -z "${WORKDIR_PATH}" ] || [ ! -d "${WORKDIR_PATH}" ]; then
    echo "Error: Could not create temporary directory." >&2
    exit 1
fi
echo "Created temporary working directory: ${WORKDIR_PATH}"

# Store the current directory before changing to workdir
ORIGINAL_DIR_BEFORE_WORKDIR_CD="${PWD}"
echo "Original directory before cd to workdir: ${ORIGINAL_DIR_BEFORE_WORKDIR_CD}"

# Change into the workdir
cd "${WORKDIR_PATH}"
echo "Changed directory to $(pwd)"

# Initialize a new Git repository
echo "Initializing Git repository in ${WORKDIR_PATH}..."
git init

# Run create_skeleton.sh
# The create_skeleton.sh script is in the main project root's scripts directory
echo "Running create_skeleton.sh from ${MAIN_PROJECT_ROOT}/scripts/create_skeleton.sh..."
"${MAIN_PROJECT_ROOT}/scripts/create_skeleton.sh" --project-dir . --yes

# Create a symbolic link to the main project directory
# The Makefile generated by create_skeleton.sh will refer to the main project
# directory using the name captured in MAIN_PROJECT_NAME.
# This link makes sure that reference (e.g., <MAIN_PROJECT_NAME>/scripts/...) works.
echo "Creating symbolic link to main project: ${MAIN_PROJECT_NAME} -> ${MAIN_PROJECT_ROOT}"
ln -s "${MAIN_PROJECT_ROOT}" "${MAIN_PROJECT_NAME}"

# Inserted debugging lines
echo "--- Generated Makefile content for provision-client target (in $(pwd)/Makefile) ---"
awk '/\.PHONY: provision-client/{f=1; print; next} f && NF==0{f=0} f' Makefile
# An alternative awk if the above doesn't capture enough:
# awk '/\.PHONY: provision-client/,/^\s*$/' Makefile | grep -v "^\s*#"
echo "--- End of generated Makefile content ---"

# Set CONTAINER_CMD to docker
export CONTAINER_CMD="sudo docker"
echo "Set CONTAINER_CMD to ${CONTAINER_CMD}"

# Run make provision-client
echo "Running make provision-client..."
make CONTAINER_CMD="sudo docker" provision-client

# Run make build-env using provision_shell.sh
# The provision_shell.sh script will be inside the linked MAIN_PROJECT_NAME directory
echo "Running make build-env via ${MAIN_PROJECT_NAME}/scripts/provision_shell.sh..."
"${MAIN_PROJECT_NAME}/scripts/provision_shell.sh" "make build-env"

# Run make sim-up using provision_shell.sh
echo "Running make sim-up via ${MAIN_PROJECT_NAME}/scripts/provision_shell.sh..."
"${MAIN_PROJECT_NAME}/scripts/provision_shell.sh" "make sim-up"

echo "Test harness script operations completed in ${WORKDIR_PATH}."

# Ensure we change back to the original directory of the harness script.
echo "Changing directory back to harness script directory: ${HARNESS_DIR_TMP}"
cd "${HARNESS_DIR_TMP}" 
echo "Current directory after cd back: $(pwd)"

# Cleanup of WORKDIR_PATH is now handled by the trap EXIT.
# The explicit rm -rf below is no longer needed.
# # echo "Attempting to remove temporary working directory: ${WORKDIR_PATH}"
# # rm -rf "${WORKDIR_PATH}" 
# # if [ ! -d "${WORKDIR_PATH}" ]; then
# #   echo "Cleaned up temporary working directory: ${WORKDIR_PATH}"
# # else
# #   echo "Warning: Failed to clean up temporary working directory: ${WORKDIR_PATH}"
# # fi

echo "Test harness script finished."
exit 0
