ARG DEFAULTLANG
ARG VERSION=16.3
FROM docker.io/library/postgres:${VERSION}

ENV LANG=${DEFAULTLANG:-en_US.UTF-8}
ENV PG_MAJOR=${VERSION%.*}
RUN localedef -i ${LANG%.UTF-8} -c -f UTF-8 -A /usr/share/locale/locale.alias ${LANG}
