ARG VERSION=17.2
FROM docker.io/library/postgres:${VERSION}

ARG ADDLOCALE=de_DE.UTF-8
RUN localedef -i ${ADDLOCALE%.UTF-8} -c -f UTF-8 -A /usr/share/locale/locale.alias ${ADDLOCALE}

COPY custom-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["custom-entrypoint.sh"]

# base container repetition for clarity
EXPOSE 5432
CMD ["postgres"]
