FROM docker.io/library/haproxy:2.9.6-alpine
# based on https://github.com/Tecnativa/docker-socket-proxy
# default access is readonly (API_POST=0)
# default accessable API's are API_events, API_ping and API_version

USER root

# curl as debugging aid, setpriv to change to user haproxy
RUN apk add --no-cache curl setpriv

USER haproxy

ENV ALLOW_RESTARTS=0 \
    ALLOW_STOP=0 \
    ALLOW_START=0 \
    AUTH=0 \
    BUILD=0 \
    COMMIT=0 \
    CONFIGS=0 \
    CONTAINERS=0 \
    DISTRIBUTION=0 \
    EVENTS=1 \
    EXEC=0 \
    GRPC=0 \
    IMAGES=0 \
    INFO=0 \
    LOG_LEVEL=info \
    NETWORKS=0 \
    NODES=0 \
    PING=1 \
    PLUGINS=0 \
    POST=0 \
    SECRETS=0 \
    SERVICES=0 \
    SESSION=0 \
    SOCKET_PATH=/var/run/docker.sock \
    SWARM=0 \
    SYSTEM=0 \
    TASKS=0 \
    VERSION=1 \
    VOLUMES=0 \
    API_PORT=2375

EXPOSE 2375

USER root

# run as root, chown the inside podman socket to haproxy user,
#   droppriv to id:99:99, start haproxy with config
CMD /bin/sh -c "chown haproxy /run/podman/podman.sock && \
    cd /var/lib/haproxy && setpriv --reuid=99 --regid=99 --nnp --init-groups \
    env HOME=/var/lib/haproxy haproxy -f /usr/local/etc/haproxy/haproxy.cfg -W -db"

