FROM docker.io/library/alpine:3.19.1
# based on https://github.com/Mailu/Mailu/blob/master/optional/unbound/Dockerfile

RUN set -euxo pipefail \
  ; apk add --no-cache bash ca-certificates curl tzdata bind-tools unbound \
  ; curl -so /etc/unbound/root.hints https://www.internic.net/domain/named.cache \
  ; chown root:unbound /etc/unbound \
  ; chmod 775 /etc/unbound \
  ; /usr/sbin/unbound-anchor -a /etc/unbound/trusted-key.key || true

EXPOSE 53/udp 53/tcp 853/tcp

HEALTHCHECK CMD dig @127.0.0.1 || exit 1

CMD /usr/sbin/unbound -c /etc/unbound/unbound.conf

