FROM docker.io/library/debian:bookworm-20251020

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y systemd udev dbus lsb-release tzdata systemd-resolved iproute2 iputils-ping openssh-client python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add pts/[0-4] to /etc/securetty to allow logins via `machinectl login`
RUN printf "pts/0\npts/1\npts/2\npts/3\npts/4\n" >> /etc/securetty

# make sure systemd-networkd and systemd-resolved are running
RUN systemctl enable systemd-networkd && systemctl enable systemd-resolved

