FROM ghcr.io/linuxcontainers/alpine:3.20 AS builder
# based on https://github.com/padhi-homelab/docker_tang

ARG JOSE_COMMIT_SHA=v14
ARG TANG_COMMIT_SHA=v15

RUN apk add --no-cache --update \
  bash g++ gawk git gmp gzip meson ninja tar \
  http-parser-dev isl-dev jansson-dev mpc1-dev mpfr-dev musl-dev openssl-dev zlib-dev

RUN git clone https://github.com/latchset/jose.git \
  && cd jose && git checkout ${JOSE_COMMIT_SHA} \
  && mkdir build && cd build && meson .. --prefix=/usr/local && ninja install

RUN git clone https://github.com/latchset/tang.git \
  && cd tang && git checkout ${TANG_COMMIT_SHA} \
  && mkdir build && cd build && meson .. --prefix=/usr/local && ninja install


FROM ghcr.io/linuxcontainers/alpine:3.20

COPY --from=builder /usr/local/bin/jose /usr/local/bin/jose
COPY --from=builder /usr/local/lib/libjose.so.0  /usr/local/lib/libjose.so.0
COPY --from=builder /usr/local/lib/libjose.so.0.0.0 /usr/local/lib/libjose.so.0.0.0
COPY --from=builder /usr/local/libexec/tangd /usr/local/bin/tangd
COPY --from=builder /usr/local/libexec/tangd-keygen /usr/local/bin/tangd-keygen

RUN apk add --no-cache --update http-parser jansson openssl socat wget zlib

RUN addgroup tang && adduser --disabled-password --system --ingroup tang tang && \
    install -d /var/db && install -m 0700 -g tang -o tang -d /var/db/tang

USER tang

EXPOSE 9090
VOLUME [ "/var/db/tang" ]

CMD /usr/local/bin/tangd -l -p 9090 /var/db/tang

