FROM docker.io/archlinux/archlinux:base-devel
# archlinux container -- Provision Client
#
# to update package lists, execute from here:
# cat Containerfile | ../../scripts/requirements.sh --containerfile > Containerfile.new && mv Containerfile.new Containerfile

RUN pacman-key --init && pacman -Syu --noconfirm base-devel git doas && \
    pacman -Syu --noconfirm act age atftp dosfstools esptool gawk gettext git gnupg go jose jq knot libarchive libxslt lsb-release ncurses openssl pango python rustup udisks2 unzip uv vault wget xz zip zlib && \
    pacman -Scc --noconfirm && \
    rm -rf /var/cache/pacman/pkg/*

RUN useradd -u 1000 -U -m -d /home/user user && \
    echo 'permit nopass user as root' >> /etc/doas.conf

USER user
RUN HOME=/home/user && \
    cd $HOME && \
    mkdir -p $HOME/.config/yay && \
    echo '{ "sudobin": "doas" }' > $HOME/.config/yay/config.json && \
    git clone https://aur.archlinux.org/yay.git && \
    cd yay && \
    makepkg --noconfirm && \
    doas -u root pacman --noconfirm -U *.pkg.tar.zst && \
    cd .. && \
    doas -u root rm -rf $HOME/yay $HOME/.cargo/registry $HOME/.cache/go-build $HOME/.cache/yay && \
    doas -u root pacman -Scc --noconfirm && \
    doas -u root rm -rf /var/cache/pacman/pkg/*

RUN HOME=/home/user && \
    cd $HOME && \
    yay -Sy --noconfirm butane checkpolicy coreos-installer libsepol pulumi-git semodule-utils && \
    yay -Sc --noconfirm && \
    doas -u root rm -rf $HOME/.cargo/registry $HOME/.cache/go-build $HOME/.cache/yay && \
    doas -u root pacman -Scc --noconfirm && \
    doas -u root rm -rf /var/cache/pacman/pkg/*

USER root
RUN rm  /etc/doas.conf

USER user
CMD ["/usr/bin/bash"]
