FROM docker.io/archlinux:base-devel
#
# archlinux container -- Full featured Provision Client 
#
# to update package lists, execute from here:
# cat Containerfile | ../../requirements.sh --containerfile > Containerfile.new && mv Containerfile.new Containerfile

RUN pacman-key --init && pacman -Syu --noconfirm base-devel lsb-release git doas && \
    pacman -Syu --noconfirm  age atftp dosfstools esptool gnupg go jq knot libarchive openssl pango pulumi python-pipenv rust udisks2 vault xz zip gawk git openssl wget unzip python ncurses zlib gettext libxslt ; \
    pacman -Scc --noconfirm

RUN useradd -u 1000 -U -m -d /home/build build && \
    echo 'permit nopass build as root' >> /etc/doas.conf && \
    echo 'build ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER build

RUN HOME=/home/build && \
    cd $HOME && \
    mkdir -p $HOME/.config/yay && \
    echo '{ "SUDOCMD": "doas" }' > $HOME/.config/yay/config.json && \
    git clone https://aur.archlinux.org/yay.git && \
    cd yay && \
    makepkg --noconfirm && \
    doas -u root pacman --noconfirm -U *.pkg.tar.zst && \
    cd .. && \
    rm -rf yay && \
    yay -Sy --noconfirm  butane checkpolicy coreos-installer esphome libsepol semodule-utils ; \
    yay -Sc --noconfirm && \
    rm -rf $HOME/.cargo/registry $HOME/.cache/go-build $HOME/.cache/yay && \
    doas -u root pacman -Scc --noconfirm

CMD ["/usr/bin/bash"]
