FROM docker.io/fedora:latest
#
# fedora container -- add raspberry PI related extra files for Fedora CoreOS Boot
#
ARG RELEASE
ENV RELEASE=${RELEASE:-38}

RUN dnf install --repo=fedora -y zip rpm cpio

# This is where the ZIP will be placed
RUN mkdir /output

# Copy the script over
WORKDIR /app
COPY build.sh build.sh
RUN chmod 700 build.sh

ENTRYPOINT /app/build.sh
